# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Mark Everett'
tagline:          'brain ventilation system'
description:      'whoops, another silly idea fell out of my ear.  sorry about that.'
url:              http://blog.mynnx.com
baseurl:          /

author:
  name:           'Mark Everett'
  url:            https://twitter.com/mynnx

paginate:         5

# Custom vars
version:          2.1.0
